AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

Style/Encoding:
  Enabled: true

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/Encoding:
  Enabled: false

Style/NestedMethodDefinition:
  Enabled: false

AbcSize:
  Enabled: false

Rails/TimeZone:
  Enabled: false